"""
admin-pw-service — persist per-device peer passwords generated by branded
SupportInternal clients at first boot, so the admin UI can auto-fill the
"Connect" prompt without the end user ever seeing the password.

Auth model:
  - POST  /admin-pw/{device_id}  — client-side. HMAC-SHA256 signature of
      device_id + password + timestamp, keyed with ADMIN_PW_HMAC_KEY.
      Enforces |now - ts| < 300 s and rejects overwrites once the row has
      been onboarded (first GET switches onboarded from 1 to 0).
  - GET   /admin-pw/{device_id}  — admin-side. HS256 JWT signed with
      ADMIN_PW_JWT_KEY (same secret as rustdesk-api).
  - DELETE /admin-pw/{device_id} — admin-side JWT. Frees the slot.
  - GET   /healthz               — unauth, for Docker healthcheck.

Storage is a single SQLite file under ADMIN_PW_DB_PATH (default
/data/admin-pw.db). No migration framework — schema is one CREATE TABLE
IF NOT EXISTS on startup.
"""

from __future__ import annotations

import hashlib
import hmac
import os
import sqlite3
import time
from contextlib import contextmanager
from typing import Iterator

import jwt
from fastapi import Depends, FastAPI, Header, HTTPException, Path
from fastapi.responses import JSONResponse
from pydantic import BaseModel, Field

# ---------------------------------------------------------------------------
# Env contract
# ---------------------------------------------------------------------------
HMAC_KEY = os.environ.get("ADMIN_PW_HMAC_KEY", "").encode()
JWT_KEY = os.environ.get("ADMIN_PW_JWT_KEY", "")
DB_PATH = os.environ.get("ADMIN_PW_DB_PATH", "/data/admin-pw.db")
ALLOW_REREGISTER = os.environ.get("ADMIN_PW_ALLOW_REREGISTER") == "1"
# Accept a previous HMAC key during key rotation (comma-separated not needed
# — one previous key is enough; the next rotation overwrites this one).
HMAC_KEY_PREV = os.environ.get("ADMIN_PW_HMAC_KEY_PREV", "").encode()

if not HMAC_KEY or not JWT_KEY:
    # Fail closed at import time so a misconfigured stack never silently
    # accepts unauthenticated writes.
    raise RuntimeError("ADMIN_PW_HMAC_KEY and ADMIN_PW_JWT_KEY must both be set")

CLOCK_SKEW_SECONDS = 300

# ---------------------------------------------------------------------------
# SQLite
# ---------------------------------------------------------------------------
@contextmanager
def db() -> Iterator[sqlite3.Connection]:
    conn = sqlite3.connect(DB_PATH, isolation_level=None)
    conn.row_factory = sqlite3.Row
    try:
        yield conn
    finally:
        conn.close()


def _init_db() -> None:
    with db() as conn:
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS device_passwords (
                device_id  TEXT PRIMARY KEY,
                password   TEXT NOT NULL,
                created_at INTEGER NOT NULL,
                updated_at INTEGER NOT NULL,
                onboarded  INTEGER NOT NULL DEFAULT 1
            )
            """
        )
        conn.execute("CREATE INDEX IF NOT EXISTS idx_updated ON device_passwords(updated_at)")


_init_db()


# ---------------------------------------------------------------------------
# Crypto helpers
# ---------------------------------------------------------------------------
def _verify_hmac(device_id: str, password: str, ts: int, sig_hex: str) -> bool:
    """Constant-time verify. Accepts current key or previous (rotation window)."""
    msg = f"{device_id}:{password}:{ts}".encode()
    expected = hmac.new(HMAC_KEY, msg, hashlib.sha256).hexdigest()
    if hmac.compare_digest(expected, sig_hex):
        return True
    if HMAC_KEY_PREV:
        expected_prev = hmac.new(HMAC_KEY_PREV, msg, hashlib.sha256).hexdigest()
        if hmac.compare_digest(expected_prev, sig_hex):
            return True
    return False


def _require_admin_jwt(authorization: str = Header(default="")) -> None:
    if not authorization.startswith("Bearer "):
        raise HTTPException(status_code=401, detail="missing bearer token")
    token = authorization[len("Bearer ") :]
    try:
        jwt.decode(token, JWT_KEY, algorithms=["HS256"])
    except jwt.InvalidTokenError as e:
        raise HTTPException(status_code=401, detail=f"invalid token: {e}") from None


# ---------------------------------------------------------------------------
# FastAPI
# ---------------------------------------------------------------------------
app = FastAPI(title="admin-pw-service", docs_url=None, redoc_url=None, openapi_url=None)


class RegisterBody(BaseModel):
    password: str = Field(min_length=8, max_length=128)
    hmac: str = Field(min_length=64, max_length=64, pattern=r"^[0-9a-fA-F]{64}$")
    ts: int


@app.get("/healthz")
def healthz() -> dict[str, str]:
    return {"status": "ok"}


@app.post("/admin-pw/{device_id}", status_code=201)
def register(device_id: str, body: RegisterBody) -> JSONResponse:
    # 1. Timestamp freshness (defeats trivial replay).
    now = int(time.time())
    if abs(now - body.ts) > CLOCK_SKEW_SECONDS:
        raise HTTPException(status_code=400, detail="timestamp out of window")

    # 2. HMAC signature.
    if not _verify_hmac(device_id, body.password, body.ts, body.hmac):
        raise HTTPException(status_code=401, detail="invalid signature")

    # 3. Anti-takeover. If a row already exists AND has been onboarded
    #    (some admin already fetched it), refuse to overwrite. This blocks
    #    a compromised HMAC_KEY from silently hijacking a device.
    #    ADMIN_PW_ALLOW_REREGISTER=1 opens an amnesty window for recovery.
    with db() as conn:
        row = conn.execute(
            "SELECT onboarded FROM device_passwords WHERE device_id = ?",
            (device_id,),
        ).fetchone()
        if row is not None and row["onboarded"] == 0 and not ALLOW_REREGISTER:
            raise HTTPException(
                status_code=409,
                detail="device already onboarded; DELETE first or enable amnesty",
            )
        conn.execute(
            """
            INSERT INTO device_passwords (device_id, password, created_at, updated_at, onboarded)
            VALUES (?, ?, ?, ?, 1)
            ON CONFLICT(device_id) DO UPDATE SET
                password = excluded.password,
                updated_at = excluded.updated_at,
                onboarded = 1
            """,
            (device_id, body.password, now, now),
        )

    return JSONResponse({"status": "registered", "device_id": device_id}, status_code=201)


@app.get("/admin-pw/{device_id}", dependencies=[Depends(_require_admin_jwt)])
def fetch(device_id: str = Path(...)) -> dict[str, str]:
    with db() as conn:
        row = conn.execute(
            "SELECT password, onboarded FROM device_passwords WHERE device_id = ?",
            (device_id,),
        ).fetchone()
        if row is None:
            raise HTTPException(status_code=404, detail="not registered")
        # First GET flips onboarded 1→0. Subsequent GETs keep working but
        # further POSTs will be refused (anti-takeover).
        if row["onboarded"] == 1:
            conn.execute(
                "UPDATE device_passwords SET onboarded = 0 WHERE device_id = ?",
                (device_id,),
            )
    return {"device_id": device_id, "password": row["password"]}


@app.delete("/admin-pw/{device_id}", dependencies=[Depends(_require_admin_jwt)])
def revoke(device_id: str) -> dict[str, str]:
    with db() as conn:
        cur = conn.execute(
            "DELETE FROM device_passwords WHERE device_id = ?", (device_id,)
        )
    if cur.rowcount == 0:
        raise HTTPException(status_code=404, detail="not registered")
    return {"device_id": device_id, "status": "revoked"}
